require("martincartledge.plugins-setup")
require("martincartledge.core.options")
require("martincartledge.core.keymaps")
require("martincartledge.core.colorscheme")
require("martincartledge.plugins.comment")
require("martincartledge.plugins.nvim-tree")
